BirdClubInfoHub/Controllers/BlogsController.cs
using AutoMapper;
using BirdClubInfoHub.Data;
using BirdClubInfoHub.Filters;
using BirdClubInfoHub.Models.DTOs;
using BirdClubInfoHub.Models.Entities;
using BirdClubInfoHub.Models.Statuses;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BirdClubInfoHub.Controllers
{
    public class BlogsController : Controller
    {
        private readonly BcmsDbContext _dbContext;
        private readonly IMapper _mapper;
        private const int PageSize = 10; //TODO move to config?

        public BlogsController(BcmsDbContext dbContext, IMapper mapper)
        {
            _dbContext = dbContext;
            _mapper = mapper;
        }

        public ActionResult GetImageFromBytes(int id)
        {
            Blog? blog = _dbContext.Blogs.Find(id);
            if (blog == null)
            {
                return NotFound();
            }
            // if thumbnail is empty return default thumbnail
            if (blog.Thumbnail == null || blog.Thumbnail.Length == 0)
            {
                return File("/img/placeholder/blog.png", "image/png");
            }
            return File(blog.Thumbnail, "image/png");
        }

        // GET: BlogsController
        public ActionResult Index(int page = 1, string keyword = "", int categoryId = 0)
        {
            IQueryable<Blog> matches = _dbContext.Blogs
                .Where(blog => blog.Status == BlogStatuses.Accepted);
            if (!string.IsNullOrEmpty(keyword))
            {
                matches = matches.Where(blog => blog.Title.ToLower().Contains(keyword.ToLower()));
            }
            if (categoryId != 0)
            {
                matches = matches.Where(blog => blog.BlogCategoryId == categoryId);
            }

            int maxPage = (int)Math.Ceiling(matches.Count() / (double)PageSize);
            if (page > maxPage)
            {
                page = maxPage;
            }
            if (page < 1)
            {
                page = 1;
            }

            List<BlogDTO> blogs = matches
                .OrderByDescending(blog => blog.DateCreated)
                .Skip((page - 1) * PageSize)
                .Take(PageSize)
                .Include(blog => blog.User)
                .Include(blog => blog.BlogCategory)
                .Select(blog => _mapper.Map<BlogDTO>(blog))
                .ToList();

            SelectList categoryOptions = new(
                _dbContext.BlogCategories,
                nameof(BlogCategory.Id),
                nameof(BlogCategory.Name));
            ViewBag.CategoryOptions = categoryOptions;

            ViewBag.NewBlogs = _dbContext.Blogs
                .Where(blog => blog.Status == BlogStatuses.Accepted)
                .OrderByDescending(blog => blog.DateCreated)
                .Take(3) //TODO move 3 to config or const
                .Select(blog => _mapper.Map<BlogDTO>(blog))
                .ToList();

            ViewBag.Page = page;
            ViewBag.Keyword = keyword;
            ViewBag.CategoryId = categoryId;
            ViewBag.MaxPage = maxPage;
            return View(blogs);
        }

        // GET: BlogsController/Details/5
        public ActionResult Details(int id)
        {
            Blog? blog = _dbContext.Blogs.Find(id);
            if (blog == null)
            {
                TempData.Add("notification", "Blog not found!");
                TempData.Add("error", "");
                return RedirectToAction("Index");
            }
            blog.User = _dbContext.Users.Find(blog.UserId)!;
            blog.BlogCategory = _dbContext.BlogCategories.Find(blog.BlogCategoryId)!;
            blog.Comments = _dbContext.Comments
                .Where(comment => comment.BlogId == blog.Id)
                .Include(comment => comment.User)
                .ToList();

            SelectList categoryOptions = new(
                _dbContext.BlogCategories,
                nameof(BlogCategory.Id),
                nameof(BlogCategory.Name));
            ViewBag.CategoryOptions = categoryOptions;
            ViewBag.NewBlogs = _dbContext.Blogs
                .Where(blog => blog.Status == BlogStatuses.Accepted)
                .OrderByDescending(blog => blog.DateCreated)
                .Take(3)
                .Select(blog => _mapper.Map<BlogDTO>(blog))
                .ToList();

            return View(_mapper.Map<BlogDTO>(blog));
        }

        [Authenticated]
        // GET: BlogsController/Create
        public ActionResult Create()
        {
            SelectList categoryOptions = new(
                _dbContext.BlogCategories,
                nameof(BlogCategory.Id),
                nameof(BlogCategory.Name));
            ViewBag.CategoryOptions = categoryOptions;
            return View();
        }

        // POST: BlogsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BlogDTO dto, IFormFile thumbnailFile)
        {
            User? user = _dbContext.Users.Find(HttpContext.Session.GetInt32("USER_ID"));
            if (user == null)
            {
                return RedirectToAction("Index", "Login");
            }
            Blog blog = _mapper.Map<Blog>(dto);
            blog.User = user;
            blog.BlogCategory = _dbContext.BlogCategories.Find(dto.BlogCategory.Id)!;
            if (thumbnailFile != null)
            {
                using MemoryStream memoryStream = new();
                thumbnailFile.CopyTo(memoryStream);
                blog.Thumbnail = memoryStream.ToArray();
            }
            blog.Status = BlogStatuses.Pending;
            _dbContext.Blogs.Add(blog);
            _dbContext.SaveChanges();

            TempData.Add("notification", "Blog submitted!");
            TempData.Add("success", "Please wait for a moderator to approve your blog.");
            return RedirectToAction("Index");
        }

        [Authenticated]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddComment(CommentDTO dto)
        {
            if (dto.User.Id == 0)
            {
                return RedirectToAction("Index", "Login");
            }
            Comment comment = _mapper.Map<Comment>(dto);
            comment.User = _dbContext.Users.Find(dto.User.Id)!;
            comment.Blog = _dbContext.Blogs.Find(dto.Blog.Id)!;
            comment.CreatedDate = DateTime.Now;
            _dbContext.Comments.Add(comment);
            _dbContext.SaveChanges();

            return RedirectToAction("Details", new { id = dto.Blog.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditComment(CommentDTO dto)
        {
            Comment? comment = _dbContext.Comments.Find(dto.Id);
            if (comment == null)
            {
                TempData.Add("notification", "Comment not found!");
                TempData.Add("error", "");
                return RedirectToAction("Index");
            }
            comment.Contents = dto.Contents;
            comment.ModifiedDate = DateTime.Now;
            _dbContext.Comments.Update(comment);
            _dbContext.SaveChanges();

            return RedirectToAction("Details", new { id = dto.Blog.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteComment(int id)
        {
            Comment? comment = _dbContext.Comments.Find(id);
            if (comment == null)
            {
                TempData.Add("notification", "Comment not found!");
                TempData.Add("error", "");
                return RedirectToAction("Index");
            }
            _dbContext.Comments.Remove(comment);
            _dbContext.SaveChanges();

            return RedirectToAction("Details", new { id = comment.BlogId });
        }
    }
}

BirdClubInfoHub/Controllers/ProfileController.cs
using AutoMapper;
using BirdClubInfoHub.Data;
using BirdClubInfoHub.Filters;
using BirdClubInfoHub.Models.DTOs;
using BirdClubInfoHub.Models.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BirdClubInfoHub.Controllers
{
    public class ProfileController : Controller
    {
        private readonly BcmsDbContext _dbContext;
        private readonly IMapper _mapper;

        public ProfileController
            (BcmsDbContext dbContext, IMapper mapper)
        {
            _dbContext = dbContext;
            _mapper = mapper;
        }

        public ActionResult GetImageFromBytes(int id)
        {
            User? user = _dbContext.Users.Find(id);
            if (user == null)
            {
                return NotFound();
            }
            //if image is empty return default
            if (user.ProfilePicture == null || user.ProfilePicture.Length == 0)
            {
                return File("/img/placeholder/user.jpg", "image/png");
            }
            return File(user.ProfilePicture, "image/png");
        }

        // GET: ProfileController
        [Authenticated]
        public ActionResult Index()
        {
            int? userID = HttpContext.Session.GetInt32("USER_ID");
            User? user = _dbContext.Users.Find(userID);
            if (user == null)
            {
                return RedirectToAction("Index", "Login");
            }
            return View(_mapper.Map<UserDTO>(user));
        }

        // GET: ProfileController/Edit/5
        [Authenticated]
        public ActionResult Edit(int id)
        {
            int? userID = HttpContext.Session.GetInt32("USER_ID");
            User? user = _dbContext.Users.Find(id);
            if (user == null || id != userID)
            {
                return RedirectToAction("Index", "Login");
            }
            return View(_mapper.Map<UserDTO>(user));
        }

        // POST: ProfileController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserDTO dto)
        {
            User? user = _dbContext.Users.Find(dto.Id);
            if (user == null)
            {
                return RedirectToAction("Index", "Login");
            }
            user.Name = dto.Name;
            user.Address = dto.Address;
            user.Phone = dto.Phone;
            _dbContext.Users.Update(user);
            _dbContext.SaveChanges();

            TempData.Add("notification", "Profile updated!");
            TempData.Add("success", "");
            return RedirectToAction("Index");
        }

        // GET: ProfileController/ChangeProfilePicture/5
        [Authenticated]
        public ActionResult ChangeProfilePicture(int id)
        {
            int? userID = HttpContext.Session.GetInt32("USER_ID");
            User? user = _dbContext.Users.Find(id);
            if (user == null || id != userID)
            {
                return RedirectToAction("Index", "Login");
            }
            return View(_mapper.Map<UserDTO>(user));
        }

        // POST: ProfileController/ChangeProfilePicture/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangeProfilePicture(int id, IFormFile profilePicture)
        {
            User? user = _dbContext.Users.Find(id);
            if (user == null)
            {
                return RedirectToAction("Index", "Login");
            }
            using (MemoryStream memoryStream = new())
            {
                profilePicture.CopyTo(memoryStream);
                user.ProfilePicture = memoryStream.ToArray();
            }
            _dbContext.Users.Update(user);
            _dbContext.SaveChanges();

            TempData.Add("notification", "Profile picture updated!");
            TempData.Add("success", "");
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword(IFormCollection formCollection)
        {
            string oldPassword = formCollection["OldPassword"].ToString();
            string newPassword = formCollection["NewPassword"].ToString();
            string confirmPassword = formCollection["ConfirmPassword"].ToString();
            User? user = _dbContext.Users.Find(HttpContext.Session.GetInt32("USER_ID"));
            if (user == null)
            {
                TempData.Add("notification", "Account not found!");
                TempData.Add("error", "");
                return RedirectToAction("Index", "Login");
            }
            PasswordHasher<User> passwordHasher = new();
            if (passwordHasher.VerifyHashedPassword(user, user.Password, oldPassword) == PasswordVerificationResult.Failed)
            {
                TempData.Add("notification", "Incorrect old password!");
                TempData.Add("error", "");
                return RedirectToAction("Index");
            }
            if (oldPassword == newPassword)
            {
                TempData.Add("notification", "New password can not be identical to old password!");
                TempData.Add("error", "");
                return RedirectToAction("Index");
            }
            if (newPassword != confirmPassword)
            {
                TempData.Add("notification", "Password does not match!");
                TempData.Add("error", "");
                return RedirectToAction("Index");
            }
            user.Password = passwordHasher.HashPassword(user, newPassword);
            _dbContext.Users.Update(user);
            _dbContext.SaveChanges();

            TempData.Add("notification", "Change password successful!");
            TempData.Add("success", "");
            return RedirectToAction("Index");
        }
    }
}

BirdClubInfoHub/Views/BlogHistory/Details.cshtml
@model BlogDTO

@section Styles
{
    <link rel="stylesheet" href="~/css/blog-history/detail.css" />
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
}

@{
    ViewData["Title"] = "Details";
    string title = Model.Title.Length > 20 ? Model.Title.Remove(20) + "..." : Model.Title;
}

<section class="blog-section">
    <div class="blog-comment-container">
        <div class="blog-container">
            <div class="blog-thumbnail-container">
                <img class="blog-thumbnail" src="@Url.Action("GetImageFromBytes", "Blogs", new { id = Model.Id })" alt="thumbnail" />
            </div>

            <div class="blog-body">
                <div class="blog-info-container">
                    <div class="blog-author-info-container">
                        <div class="blog-author-ava-container">
                            <img class="blog-author-ava" src="@Url.Action("GetImageFromBytes", "Profile", new { id = Model.User.Id })" alt="author" />
                        </div>

                        <p class="blog-author-name">By @Model.User.Name</p>
                    </div>

                    <p class="blog-create-date">@Model.DateCreated.ToString("dd MMMM, yyyy")</p>
                </div>

                <h2 class="blog-title">@Model.Title</h2>

                <div class="blog-content">@Html.Raw(Model.Contents)</div>
            </div>
        </div>
    </div>

    <div class="blog-utils-container">
        <a class="edit-blog-button" asp-action="Edit" asp-route-id="@Model.Id">Edit Blog</a>
        <div class="search-form">
            <form>
                <div class="select">
                    <select name="categoryId" class="category-list" asp-items="@ViewBag.CategoryOptions" disabled>
                        <option value="">All</option>
                    </select>
                </div>

                <div class="search-group">
                    <input name="keyword" type="text" placeholder="Search by title" value="@ViewBag.Keyword" disabled />
                </div>

                <div class="pagination">
                    Page <input name="page" value="1" disabled /> of 1
                </div>
                <button class="search-button" type="submit">
                    <i class="fa-solid fa-magnifying-glass"></i>
                </button>
            </form>
        </div>
        <div class="latest-blogs-container">
            <h2>Latest News</h2>
            <div class="latest-blog">
                <div class="latest-blog-thumbnail-container">
                    <img class="latest-blog-thumbnail" src="@Url.Action("GetImageFromBytes", "Blogs", new { id = Model.Id })" alt="thumbnail" />
                </div>

                <div class="latest-blog-title">@title</div>
            </div>
        </div>
    </div>
</section>

@section Scripts
{
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/js/blog/detail.js"></script>
}

BirdClubInfoHub/Views/BlogHistory/Edit.cshtml
@model BlogDTO

@{
    ViewData["Title"] = "Edit";
}

@section Styles
{
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/css/blog/create.css" />
}

<section class="create-blog-container">
    <a class="create-blog-back-button" asp-action="Index">
        <i class="fa-solid fa-backward"></i>
        Back
    </a>

    <form class="create-blog-form" asp-action="Edit" enctype="multipart/form-data">
        <input type="hidden" asp-for="Id" />

        <h2>Edit blog</h2>

        <div class="input-container">
            <label class="input-label" for="blog-category">Category</label>
            <select id="blog-category" class="input" asp-for="BlogCategory.Id" asp-items="ViewBag.CategoryOptions">
                <option value="7" hidden>Choose a category</option>
            </select>
            <span asp-validation-for="BlogCategory.Id" class="text-danger"></span>
        </div>

        <div class="input-container">
            <label class="input-label" for="blog-title">Title</label>
            <input id="blog-title" class="input" asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>

        <div class="input-container">
            <label for="blog-contents" class="input-label blog-content-label">Contents</label>
            <textarea id="blog-contents" name="Contents">
                @Html.Raw(Model.Contents)
            </textarea>
        </div>

        <div class="input-container">
            <p class="input-label">Thumbnail</p>
            <div class="blog-thumbnail-container">
                <label for="blog-thumbnail" class="input-label thumbnail-submit-button">Choose a thumbnail</label>
                <input id="blog-thumbnail" class="input" type="file" name="thumbnailFile" accept="image/*" onchange="loadFile(event)" />
            </div>
            <img id="preview-thumbnail" src="@Url.Action("GetImageFromBytes", "Blogs", new { id = Model.Id })" />
        </div>

        <input class="create-blog-create-button" type="submit" value="Save" />
    </form>
</section>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
        await Html.RenderPartialAsync("_Summernote", new { Height = 500, Selector = "#blog-contents" });
    }
    <script src="~/js/blog-history/edit.js"></script>
}

BirdClubInfoHub/Views/BlogHistory/Index.cshtml
@model IEnumerable<BlogDTO>

@{
    ViewData["Title"] = "Index";
}

@section Styles {
    <link rel="stylesheet" href="~/css/reset.css" />
    <link rel="stylesheet" href="~/css/list.css" />
    <link rel="stylesheet" href="~/css/search-form.css" />
}

<section class="table-header">
    <h2>Blog history</h2>
    @if (!string.IsNullOrEmpty(ViewBag.Keyword) || !string.IsNullOrEmpty(ViewBag.Status))
    {
        <h4>Search results</h4>
    }
</section>
<div class="option">
    <a class="button action-button" asp-action="Create" asp-controller="Blogs">
        <i class="fa-solid fa-circle-plus"></i>
        Create new blog
    </a>
</div>
<div class="search-form">
    <form method="get" asp-action="Index">
        <div class="select">
            <select name="status" data-selected="@ViewBag.Status" class="status-list">
                <option value="">All</option>
                <option value="@BlogStatuses.Accepted">
                    @BlogStatuses.Convert(BlogStatuses.Accepted)
                </option>
                <option value="@BlogStatuses.Pending">
                    @BlogStatuses.Convert(BlogStatuses.Pending)
                </option>
                <option value="@BlogStatuses.Rejected">
                    @BlogStatuses.Convert(BlogStatuses.Rejected)
                </option>
            </select>
        </div>

        <div class="search-group">
            <input name="keyword" type="text" placeholder="Search by title" value="@ViewBag.Keyword" />
            <button class="search-button" type="submit">
                <i class="fa-solid fa-magnifying-glass"></i>
            </button>
        </div>

        <br />
        <div class="pagination">
            <p>Page <input name="page" value="@ViewBag.Page" /> of @ViewBag.MaxPage</p>
        </div>
    </form>
</div>
<div class="sticky-table">
    <table>
        <thead>
            <tr>
                <th>Title</th>
                <th>Category</th>
                <th>Date created / modified</th>
                <th>Status</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                string title = item.Title.Length > 30 ? item.Title.Remove(30) + "..." : item.Title;
                <tr>
                    <td>@title</td>
                    <td>@item.BlogCategory.Name</td>
                    <td>@item.DateCreated</td>
                    <td>@BlogStatuses.Convert(item.Status)</td>
                    <td class="option">
                        @if (item.Status == BlogStatuses.Accepted)
                        {
                            <a class="button action-button" asp-action="Details" asp-controller="Blogs" asp-route-id="@item.Id">
                                <i class="fa-solid fa-eye"></i>
                            </a>
                        }
                        @if (item.Status == BlogStatuses.Pending)
                        {
                            <a class="button action-button" asp-action="Details" asp-route-id="@item.Id">
                                <i class="fa-solid fa-eye"></i>
                            </a>
                            <a class="button action-button" asp-action="Edit" asp-route-id="@item.Id">
                                <i class="fa-solid fa-pen-to-square"></i>
                            </a>
                            <a class="button delete-button" onclick="initDelete(@item.Id)">
                                <i class="fa-solid fa-trash"></i>
                            </a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="delete-container">
    <form class="delete-form" asp-action="Delete">
        <h2>Are you sure you want to delete this blog?</h2>
        <p>This action cannot be undone!</p>

        <input type="hidden" id="blog-id" name="Id" />

        <div class="delete-control">
            <input class="button delete-button" type="submit" value="Delete" />
            <button class="button cancel-button" type="button" onclick="cancelDelete()">Cancel</button>
        </div>
    </form>
</div>

@section Scripts {
    <script src="~/js/blog-history/index.js"></script>
}